version: "3.8"
services:
  express-node-app:

    build:        
      context: .
      target: production
    # volumes:
    #   - ./src:/app/src:ro
    
    environment:
      - NODE_ENV=production
  
    command: npm start
      


    