# version: '3.8'

services:
  express-node-app:
    build: 
      context: .
      target: development
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
    command: npm run start-dev
